- hosts: minecraft-servers

  vars:
    mc_home: /opt/minecraft

  tasks:
    - name: Create Minecraft directory
      file: 
        path: "{{mc_home}}"
        state: directory

    - name: Copy BuildTools.jar
      copy:
        src: ../files/minecraft/BuildTools.jar
        dest: "{{mc_home}}"

    - name: Running BuildTools.jar
      command:  "chdir={{mc_home}} java -jar BuildTools.jar"

    - name: Copy Eula file
      copy:
        src: ../files/minecraft/eula.txt
        dest: "{{mc_home}}"

    - name: Create TMP
      file:
        path: "{{mc_home}}/tmp"
        state: directory
    
    - name: Copy scripts
      copy:
        src: "{{ item }}"
        dest: "{{mc_home}}"
        mode: u=rx,g=r,o=r
      with_items:
        - ../files/minecraft/scripts/start.sh
        - ../files/minecraft/scripts/stop.sh
        - ../files/minecraft/scripts/restart.sh
  
    - name: Permitions
      file:
        path: "{{mc_home}}"
        owner: ec2-user
        group: ec2-user
        recurse: true
      
    - name: Prepare start
      command: echo "Start minecraft server"
      notify: "Start minecraft server"
      become: false

  handlers:
    - name: Start minecraft server
      command: "/opt/minecraft/start.sh"
      listen: "Start minecraft server"
      become: false
      